# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import document_pb2 as document__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x0epactline.ai.v1\x1a\x0e\x64ocument.proto\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\xae\x01\n\x0e\x45xtractRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x13\n\x0bparsed_text\x18\x02 \x01(\t\x12\x33\n\x08segments\x18\x03 \x03(\x0b\x32!.pactline.document.v1.TextSegment\x12\x13\n\x0b\x66ield_names\x18\x04 \x03(\t\x12\x10\n\x08model_id\x18\x05 \x01(\t\x12\x16\n\x0eprompt_version\x18\x06 \x01(\t\"A\n\x0f\x45xtractResponse\x12.\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1e.pactline.ai.v1.ExtractedField\"s\n\x0e\x45xtractedField\x12\x12\n\nfield_name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nvalue_json\x18\x03 \x01(\t\x12*\n\x08\x63itation\x18\x04 \x01(\x0b\x32\x18.pactline.ai.v1.Citation\"\x93\x01\n\x08\x43itation\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07locator\x18\x02 \x01(\t\x12\x12\n\nspan_start\x18\x03 \x01(\x05\x12\x10\n\x08span_end\x18\x04 \x01(\x05\x12\x10\n\x08model_id\x18\x05 \x01(\t\x12\x16\n\x0eprompt_version\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t2\x9f\x01\n\x02\x41I\x12G\n\x06Health\x12\x1d.pactline.ai.v1.HealthRequest\x1a\x1e.pactline.ai.v1.HealthResponse\x12P\n\rExtractFields\x12\x1e.pactline.ai.v1.ExtractRequest\x1a\x1f.pactline.ai.v1.ExtractResponseB>Z<github.com/rupivbluegreen/pactline/internal/ai/aigrpc;aigrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/rupivbluegreen/pactline/internal/ai/aigrpc;aigrpc'
  _globals['_HEALTHREQUEST']._serialized_start=44
  _globals['_HEALTHREQUEST']._serialized_end=59
  _globals['_HEALTHRESPONSE']._serialized_start=61
  _globals['_HEALTHRESPONSE']._serialized_end=93
  _globals['_EXTRACTREQUEST']._serialized_start=96
  _globals['_EXTRACTREQUEST']._serialized_end=270
  _globals['_EXTRACTRESPONSE']._serialized_start=272
  _globals['_EXTRACTRESPONSE']._serialized_end=337
  _globals['_EXTRACTEDFIELD']._serialized_start=339
  _globals['_EXTRACTEDFIELD']._serialized_end=454
  _globals['_CITATION']._serialized_start=457
  _globals['_CITATION']._serialized_end=604
  _globals['_AI']._serialized_start=607
  _globals['_AI']._serialized_end=766
# @@protoc_insertion_point(module_scope)
