# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x0epactline.ai.v1\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2M\n\x02\x41I\x12G\n\x06Health\x12\x1d.pactline.ai.v1.HealthRequest\x1a\x1e.pactline.ai.v1.HealthResponseB>Z<github.com/rupivbluegreen/pactline/internal/ai/aigrpc;aigrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/rupivbluegreen/pactline/internal/ai/aigrpc;aigrpc'
  _globals['_HEALTHREQUEST']._serialized_start=28
  _globals['_HEALTHREQUEST']._serialized_end=43
  _globals['_HEALTHRESPONSE']._serialized_start=45
  _globals['_HEALTHRESPONSE']._serialized_end=77
  _globals['_AI']._serialized_start=79
  _globals['_AI']._serialized_end=156
# @@protoc_insertion_point(module_scope)
